### PR TITLE
Add Optimized BatchTokenizer, Leave Others Unchanged

### PR DESCRIPTION
**Pull request by alexandermorgan**
Add an optimized "batch tokenizer" and leave other tokenizers unchanged. This PR completes the first "TODO" in the README by adding the batch tokenizer which has the same functionality as the regex tokenizer, but trains ~90X faster, and also encodes and decodes a bit faster. Also updates the README and train.py files accordingly, and adds a test that demonstrates that the regex and batch tokenizers produce equivalent tokenizations.

## Main Optimizations
1. Safely batching merges to reduce the number of calls to `get_stats` and `merge` (actually now `multi_merge`). "Safely" means respecting which combinations of bytes are merged, and keeping them in a non-problematic order. They aren't merged in the same exact order, but the slight shifts to the order of merges are only performed when we can be sure that all texts would get tokenized the same way.
2. Use bytes objects and lists interchangeably. For the purposes of this repo, bytes objects already have all the functionality we need from lists, so there's never a reason to unpack a bytes object into a new list just so you can work with it. In other words:
```
li = [97, 98]
by = bytes(b'cd')
li.extend(by) # -> li will be [97, 98, 99, 100]
```
3. `get_stats` and `multi_merge` change values in place.
4. Use collections.defaultdict and heapq.nlargest.

There were smaller things too. This deep dive has been a lot of fun! Thanks for making this topic so much more accessible.

### CODE REVIEW

**Comment by alexandermorgan** [comment]
With the latest commits and in python 3.12 this is much faster:

- training runtime reduced ~98.7%
- encoding runtime reduced ~80%
- decoding runtime reduced ~15%

It would be great to try this using the jit-compiled version of python 3.13 and also the no-gil 3.13 version. I tried the May beta version of 3.13 and it was a little faster, but importing tiktoken no longer worked. I couldn't figure out how to build the jit-compiled and no-gil versions of python 3.13, but these seem like the most promising ways to get further speed improvements here.

The current goal is make this performant enough to be able to comfortably train a full ~100k vocab on gigabytes or even terabytes of data on a laptop. I want it to be easy for people to experiment with new tokenization approaches at a scale where they can train them and be confident they're actually better/worse without needing special hardware. I think the only other thing necessary for that goal is to manage the processing of big files that don't fit in memory.

**Comment by Majdoddin** [comment]
Not breaking after hitting a collision and just skipping it, can lead to a suboptimil vocab compared to BPE. Here is a minimalistic example:
Let the text chunks in `ids` (after applying regex to text) be:
```python
ids = [b'aa...a', b'aa...a', ..., b'aa...a', b'yz']
```
So b'aa...a', of length 32, is repeated, say, a million times, and b'yz' just once. Suppose we can do 5 merges. Clearly BPE adds just these tokens to the vocab: &beta;=aa, &beta;<sup>2</sup>, ..., &beta;<sup>5</sup>. The merger of yz is not in the final vocab.

Now, in your code, in the first iteration of `while`, all the merges are from original characters (because there is no mergers yet). Assuming `max_clutch_size =2`, the first pair to merge is aa; and the second pair is yz. Thus a different vocab, with 50% efficiency compared to BPA.
```python
        while merges_remaining > 0:
            seen_first = set() # set of ints that were seen in the first position in pairs
            seen_last = set() # set of ints that were seen in the last position in pairs
            pairs_to_merge = {}
            # count the number of times every consecutive pair appears
            stats = get_stats(ids)
            # find the pairs with the highest counts
            # use min to make sure you don't consider pairs beyond the vocab size
            top_pairs = nlargest(min(max_batch_size, merges_remaining), stats, key=stats.get)
            for first, last in top_pairs:  # pairs are (first, last) tuples
                if first in seen_last or last in seen_first:
                    # skip this pair because it overlaps with a previous pair
                    # still add it to the seen sets to avoid future overlaps
                    seen_first.add(first)
                    seen_last.add(last)
                    continue # skip this pair but keep looking for mergeable top_pairs
```

Using more involved data structures, it is possible to cut the number of merges dramatically, while still getting the same vocab. See issue #5.

**Comment by alexandermorgan** [comment]
Interesting example, but that is not how aaaaa...aaaayz would get merged. When you get to 'ay', the 'a' would trigger the `if first in seen_last or last in seen_first:` condition, because 'a' has shown up previously as the last element in a previous pair, so it meets the `last in seen_first` part of the condition. Critically though, 'ay' also get added to the `seen_first` and `seen_last` sets before the `continue`. This means that when you get to the 'yz' pair, that pair will also get skipped since 'y' will be in the `seen_last` set, and now appears first. That triggers the `first in seen_last` part of the condition.

In addition, while I know this is just an example, you would never train a text of 34 characters with a vocab of 33 new tokens, which is the length of `top_pairs` it would take to get all the way to the last pair on the first try.

If the `continue` is still bothersome, you can replace `continue` with a `break` and then you have a further layer of reassurance that merges won't get made that don't belong in the vocab. With `break` instead it's obviously not as fast but it's still a pretty solid speed up.

If you want to find a problematic case, it's pretty easy to train the regex tokenizer on a test text. If it makes merges that the basic tokenizer wouldn't, I would really appreciate knowing about it! The thing is that the respective merges dictionaries will not be in the same order, but their `dict.keys()` objects (~basically sets) should be equal.

**Comment by Majdoddin** [comment]
Thank you for your answer. I edited my previous comment to make things clear.

As you mentioned, this exaggerated example is to demonstrate that rare pairs can get into the vocab. In practice it may lead to just a little loss in compression, but even 1% is a lot, because it directly affects the throughput of the LLM.

As said, issue #5 discusses the way to cut the number of merges from V, size of vocab, to log(V), guaranteed with same vocab. But that is beyond the purpose of this PR as a python optimization. So as you said, just replacing `continue` with `break` seems the proper thing here.

And I went through your PR closely, very solid indeed. Educational for me.

**Comment by alexandermorgan** [comment]
Thinking about it more, you have a point. I misspoke earlier when I said the there were 33 merge candidates in a sequence of 34 characters. Since this is only unique pairs at this stage, 'aaaa...aaayz' would be only three candidates, 'aa', 'ay', and 'yz' and they would merge as I mentioned before. But if the sequence were 'aaaa...aaayzyz', then the top two pairs would be 'aa' followed by 'yz', so even if you had a batch of just two merges, you would merge 'yz' before merging token 256 ('aa') with another 256. This approach does allow for things to happen out of order, but the idea is that there are still multiple batches so this would merge 256 and 256 on the next batch. So, if you had a situation like this where you made a merge where the new token would repeat many times in a row once merged into the sequence, and that happened on your last batch, then that would impact the vocabulary.

I think it's probably fine if the 100,001st most-common merge happens instead of the 100,000th merge if we're talking about a 100k vocab, but you definitely have a point. Maybe a good simple solution would be to have the last ~10 merges be simple ones. I'll have to keep thinking about it. Thanks for pointing this out!

**Comment by Majdoddin** [comment]
Please note that the example is about `regex.py`, not `simple.py`.

**Comment by alexandermorgan** [comment]
Closing because my fork has developed enough to have a different objective from minbpe's educational one. My fork's purpose is now to facilitate experiments with the tokenization process by providing a fast, lightweight, and pure-python implementation that can build a vocab from gigabytes of text on a basic laptop in minutes. This involves things like safely batching merges, saving/loading dictionary representations of datasets, support for the datasets library, special handling of stop words, etc. which are important things to have for a research-grade tokenizer but would overcomplicate the educational purpose of this repo. I'm happy to make a different pr adding a link to a "notable forks" section if that's wanted.

**Pull request closed without merging**
